name: "List tags history"
description: "List recent tags from a repository"
inputs:
  token:
    description: "Github Token"
    required: true
  query:
    description: "Query to filter tags"
    default: ""
  limit:
    description: "Limit of tags to list"
    default: "10"
outputs:
  current-tag:
    description: "Current tag"
    value: ${{ steps.get-tags-history.outputs.current-tag }}
  latest-tag:
    description: "Latest tag"
    value: ${{ steps.get-tags-history.outputs.latest-tag }}

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      id: get-tags-history
      with:
        github-token: ${{ inputs.token }}
        script: |
          const [owner, repositoryName] = "${{github.repository}}".split("/");
          const refPrefix = "refs/tags/";

          const query = `{
              repository(owner: "${owner}", name: "${repositoryName}") {
                  refs(refPrefix: "${refPrefix}", query: "${{inputs.query}}"
                  , first: ${{inputs.limit}}, orderBy: {field: TAG_COMMIT_DATE, direction: DESC}) {
                      edges {
                          node {
                              name
                              target {
                              oid
                              ... on Tag {
                                      message
                                      commitUrl
                                      tagger {
                                          name
                                          email
                                          date
                                      }
                                  }
                              }
                          }
                      }
                  }
              }
          }`;

          const graphQLResponse = await github.graphql({
            query,
          });

          const tagsHistory = graphQLResponse?.repository?.refs?.edges || [];

          const currentTag = tagsHistory[0]?.node?.name || "";
          const latestTag = tagsHistory[1]?.node?.name || "";

          core.setOutput("current-tag", `${refPrefix}${currentTag}`);
          core.setOutput("latest-tag", `${refPrefix}${latestTag}`);
