name: "List tags history"
description: "List recent tags from a repository"
inputs:
  token:
    description: "Github Token"
    required: true
  limit:
    description: "Limit of tags to list"
    default: "10"
#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v3
      with:
        github-token: ${{ inputs.token }}
        script: |
          const [owner, repositoryName] = "${{github.repository}}".split("/");

          const query = `{
              repository(owner: ${owner}, name: ${repositoryName}) {
                  refs(refPrefix: "refs/tags/", query: "prod*"
                  , first: 10, orderBy: {field: TAG_COMMIT_DATE, direction: DESC}) {
                      edges {
                          node {
                              name
                              target {
                              oid
                              ... on Tag {
                                      message
                                      commitUrl
                                      tagger {
                                          name
                                          email
                                          date
                                      }
                                  }
                              }
                          }
                      }
                  }
              }
          }`;

          const tagHistory = await github.graphql({
            query,
          });

          console.info(tagHistory);
